name: Subdomain Monitor

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Enter target to monitor'
        required: true
  schedule:
    - cron: '0 0 * * *'

jobs:
  subenum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup tools directory
        run: |
          mkdir -p tools/bin lists output save
          
          echo "TOOLS_BIN=$(pwd)/tools/bin" >> $GITHUB_ENV
          echo "$(pwd)/tools/bin" >> $GITHUB_PATH

      - name: Install tools if not present
        run: |
          for tool in tools/*.sh; do
            tool_name=$(basename "$tool" .sh)
            if [ ! -f "$TOOLS_BIN/$tool_name" ]; then
              chmod +x "$tool"
              ./"$tool"
            fi
          done

      - name: Download wordlists
        run: |
          chmod +x tools/lists.sh
          ./tools/lists.sh

      - name: Update target
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "${{ github.event.inputs.target }}" > target.txt

      - name: Run subdomain enumeration
        run: |
          chmod +x monitor/subenum.sh
          if [ ! -f target.txt ] || [ ! -s target.txt ]; then
            echo "Error: No target specified"
            exit 1
          fi
          target=$(cat target.txt)
          ./monitor/subenum.sh "$target"

      - name: Send to Discord
        run: |
          chmod +x send/discord.sh
          ./send/discord.sh
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add save/ tools/bin/ target.txt
          git diff --staged --quiet || git commit -m "update [skip ci]"
          git push
